# Generated by Django 2.0 on 2018-06-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='chatting_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='box',
            name='latitude',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='box',
            name='longtitude',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
