# Generated by Django 2.0 on 2018-06-10 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatting', '0002_auto_20180605_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
